import { ArrowLeft, BookOpen, CheckCircle2, CircleAlert, FileText, ShieldCheck } from 'lucide-react';
import type { View } from '@/types';

interface NsrPageProps { onBack: () => void; onNavigate: (view: View) => void; }

export function NsrPage({ onBack, onNavigate }: NsrPageProps) {
  const levels = [
    ['Leve', 'Monitoreo', 'Daños superficiales. La vivienda puede seguir habitada.', 'green'],
    ['Moderado', 'Revisión técnica', 'Requiere evaluación detallada y reparación programada.', 'amber'],
    ['Riesgo Alto', 'Intervención urgente', 'Restringir áreas afectadas y evaluar de inmediato.', 'orange'],
    ['Riesgo Extremo', 'Evacuación', 'Edificación insegura. No ingresar sin autorización profesional.', 'red'],
  ];
  return <main className="nsr-page"><div className="section-shell"><button className="back-link dark" onClick={onBack}><ArrowLeft size={15} /> Volver al inicio</button><div className="nsr-intro"><div className="eyebrow"><span className="eyebrow-line" /> MARCO DE REFERENCIA</div><h1>¿Qué significa la <em>NSR-10</em>?</h1><p>La Norma Colombiana de Diseño y Construcción Sismo Resistente establece cómo evaluar la seguridad de las edificaciones existentes después de un evento sísmico.</p></div><div className="nsr-grid"><div className="nsr-main-card"><div className="nsr-card-icon"><BookOpen size={23} /></div><span className="mini-label">CAPÍTULO A.10</span><h2>Evaluación de la seguridad<br />de edificaciones existentes</h2><p>La aplicación traduce los criterios técnicos de la NSR-10 a señales que cualquier propietario puede observar. No reemplaza un dictamen: ayuda a reconocer cuándo pedir ayuda.</p><div className="nsr-principles"><div><CheckCircle2 size={17} /><span>Identificar el sistema estructural</span></div><div><CheckCircle2 size={17} /><span>Evaluar daños visibles después del sismo</span></div><div><CheckCircle2 size={17} /><span>Definir habitabilidad y restricciones</span></div><div><CheckCircle2 size={17} /><span>Recomendar evaluación profesional</span></div></div><button className="button button-dark" onClick={() => onNavigate('diagnosis')}>Aplicar la guía <span>→</span></button></div><div className="nsr-side"><div className="nsr-side-card"><FileText size={20} /><strong>La norma en palabras simples</strong><p>Mientras más grave sea el daño observado, menor es la confianza en que la estructura pueda resistir otro sismo.</p></div><div className="nsr-side-card warning"><CircleAlert size={20} /><strong>Una guía, no un dictamen</strong><p>Solo un profesional calificado puede declarar una edificación segura o inhabitable.</p></div></div></div><div className="nsr-levels"><div className="section-heading-row compact"><div><div className="eyebrow"><span className="eyebrow-line" /> SEMÁFORO DE HABITABILIDAD</div><h2>La acción que corresponde<br /><em>a cada nivel</em></h2></div></div><div className="nsr-level-grid">{levels.map(([name, action, description, tone]) => <div className={`nsr-level ${tone}`} key={name}><span className="level-dot" /><span className="mini-label">{action}</span><h3>{name}</h3><p>{description}</p></div>)}</div></div><div className="nsr-source"><ShieldCheck size={17} /><span>Referencia educativa basada en los principios del Capítulo A.10 de la NSR-10. Consulta siempre la versión oficial y a un profesional competente.</span></div></div></main>;
}
